version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: avito_test_db
    volumes:
      - database_data:/var/lib/postgresql/data

  api:
    build: .
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ./api:/usr/src/app/
    links:
      - db
    environment:
      DATABASE_URL: host=db port=5432 user=docker password=docker dbname=avito_test_db sslmode=disable


volumes:
  database_data:
    driver: local